name: CI MLflow Project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - run: |
          python -m pip install --upgrade pip
          pip install mlflow
          pip install -r MLProject/requirements.txt

      - run: |
          cd MLProject
          mlflow run . --env-manager=local

      - run: |
          MODEL_FILE=$(find MLProject/mlruns -type f -name MLmodel | head -n 1)
          if [ -z "$MODEL_FILE" ]; then exit 1; fi
          MODEL_DIR=$(dirname "$MODEL_FILE")
          echo "MODEL_DIR=$MODEL_DIR" >> $GITHUB_ENV

      - run: |
          mlflow models build-docker \
            --model-uri "file://$MODEL_DIR" \
            --name airquality-mlflow-model

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - run: |
          docker tag airquality-mlflow-model \
            ${{ secrets.DOCKER_HUB_USERNAME }}/airquality-mlflow-model:latest
          docker push \
            ${{ secrets.DOCKER_HUB_USERNAME }}/airquality-mlflow-model:latest
